### PR TITLE
feat: add retry functionality

### LINKED ISSUE #110: Retry functionality
Have `useResponsiveImageView` to return a call back that can be used to trigger retry load. The loading may fail for various reasons, so having retry functionality is a user-friendly thing.

### PR DESCRIPTION
**Pull request by wKovacs64**
Closes #110

### CODE REVIEW

**Comment by wKovacs64** [comment]
OK so I totally cheesed the implementation just to get it in, but I think this should satisfy your use case, @aprilmintacpineda ? Sorry it took so long.

Side note: I haven't looked at this code in a while and saw a lot of changes I'd like to make when I got in there. I probably need to redo the whole test suite and I'd rather track and represent the state differently (ideally with XState but then I'd be adding dependencies, which I'm assuming RN users may not love), etc. and saving the user from memoizing the `source` parameter is probably weird now that people are more used to hooks... but I guess these are considerations for another day.

**Comment by aprilmintacpineda** [comment]
@wKovacs64 yeah looks good to me! I think adding xstate would be overkill, it's quite a heavy dependency to add.

**Comment by wKovacs64** [comment]
> @wKovacs64 I think adding xstate would be overkill, it's quite a heavy dependency to add.

Yep, agreed.

**Pull request merged**
